end_effector_controller:
    type: position_controllers/JointTrajectoryController
    default: True
    joints:
      - joint_4

plan_controller:
    type: position_controllers/JointGroupPositionController
    default: True
    joints:
      - joint_0
      - joint_1
      - joint_2
      - joint_3
      - joint_4
    

joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 100